# Generated by Django 5.0.4 on 2024-05-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=255, verbose_name="Nom de l'établissement")),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('donation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du don')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('expiration_date', models.DateField(verbose_name="Date d'expiration")),
            ],
        ),
    ]
