# Generated by Django 5.0.4 on 2024-05-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_establishment_name_donation_noun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='expiration_date',
        ),
    ]
