# Generated by Django 5.0.4 on 2024-05-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_donation_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation',
            field=models.CharField(max_length=100, verbose_name='Montant du don'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.CharField(max_length=100, verbose_name='Quantité'),
        ),
    ]
